<?php
function entity_resolve_from_path($path, $rendered_entity = FALSE) {
  if (!entity_resolve_is_entity_path($path)) {
    return NULL;
  }

  $entity_type = entity_resolve_get_entity_type_from_path($path);

  $eid = entity_resolve_get_eid_from_path($path);

  return ($rendered_entity) ? entity_load($entity_type, array($eid)) : array($entity_type, $eid);
}

function entity_resolve_get_entity_type_from_path($path) {
  $path = entity_resolve_get_path_array($path);

  $entity_type = $path[0];

  $convert = array(
    'taxonomy' => 'taxonomy_term',
  );

  if (array_key_exists($entity_type, $convert)) {
    $entity_type = $convert[$entity_type];
  }

  return $entity_type;
}

function entity_resolve_get_path_array($path) {
  if (!is_array($path)) {
    $path = explode('/', $path);
  }

  return $path;
}

function entity_resolve_is_entity_path($path) {
  $path = entity_resolve_get_path_array($path);

  $eid = array_pop($path);

  return (!empty($path[0]) && is_string($path[0]) && is_numeric($eid));
}

function entity_resolve_get_eid_from_path($path) {
  $path = entity_resolve_get_path_array($path);

  $eid = NULL;

  while (!is_numeric($eid) && !empty($path)) {
    $eid = array_pop($path);
  }

  return $eid;
}